defaults: &defaults
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: "<%= ENV['DB_PASSWORD'] %>"
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV['DB_POOL'] %>
  charset: utf8
  # collation: utf8_bin

test:
  <<: *defaults
development:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
